[package]

name = "imap"
version = "0.9.4"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>",
           "Jon Gjengset <jon@thesquareplanet.com>"]
documentation = "https://docs.rs/imap/"
repository = "https://github.com/jonhoo/rust-imap"
homepage = "https://github.com/jonhoo/rust-imap"
description = "IMAP client for Rust"
readme = "README.md"
license = "Apache-2.0/MIT"

keywords = ["email", "imap"]
categories = ["email", "network-programming"]

[badges]
travis-ci = { repository = "jonhoo/rust-imap" }
appveyor = { repository = "jonhoo/rust-imap", branch = "master", service = "github" }
codecov = { repository = "jonhoo/rust-imap", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[lib]
name = "imap"
path = "src/lib.rs"

[dependencies]
native-tls = "0.2.2"
regex = "1.0"
bufstream = "0.1"
imap-proto = "0.6"
nom = "4.0"
base64 = "0.10"

[dev-dependencies]
lettre-openssl111 = "0.9"
lettre-openssl111_email = "0.9"
