on:
  push:
    branches: [main]
  pull_request:
name: With dependencies at minimal versions
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: cargo update -Zminimal-versions
        uses: actions-rs/cargo@v1
        with:
          command: update
          toolchain: nightly
          args: -Zminimal-versions
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features test-full-imap --all-targets
    services:
      cyrus_imapd:
        image: outoforder/cyrus-imapd-tester:latest
        ports:
          - 3025:25
          - 3143:143
          - 3465:465
          - 3993:993
